apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: quay-maistra
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: maistra
  displayName: "Maistra Operators"
  publisher: "Maistra Team"
  authorizationToken:
    secretName: quay-operators-secret