apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-maistra
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: "quay.io/maistra/olm-catalog-source:1.1.2.2"
